### ISSUE TITLE
Fulcrum lending and borrowing function examples, parameters, and return values

### ISSUE THREAD

**Issue by KadenZipfel** [bZxNetwork/docs#2]
I think it would be really valuable to flesh out the function documentation a bit by providing examples along with explaining what the parameters and return values are. Take the following example:

### mint(address,uint256)

```
function mint(
    address receiver,
    uint256 depositAmount)
    external
    returns (uint256 mintAmount);
```

Called to deposit assets to the iToken, which in turn mints iTokens to the lender’s wallet at the current tokenPrice() rate. A prior ERC20 “approve” transaction should have been sent to the asset token for an amount greater than or equal to depositAmount. The receiver address specifies the address that will receive the minted iTokens. Note: The asset token address for an iToken is returned by the loanTokenAddress() function. For iETH contracts, the expected underlying asset is WETH.

`address receiver`: The address at which the minted tokens are supplied to.
`uint256 depositAmount`: The amount of underlying asset being supplied.
`returns (uint256 mintAmount)`: The amount of minted iTokens.

**Example**

```
ERC20 underlying = ERC20(0x...); // create a variable for the underlying asset contract
iToken itoken = iToken(0x...); // create a variable for the corresponding iToken contract
underlying.approve(address(iToken), 1000); // approve the iToken an allowance to the underlying asset
assert(itoken.mint(receiver, 1000) > 0); // mint the iTokens and assert that the mint amount is greater than 0
```

**Comment by tomcbean** [comment]
Great suggestions! If you'd like to make these updates yourself, feel free to submit a PR. Thanks :)
